# Generated by Django 5.1.4 on 2025-01-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='Review',
        ),
    ]
