# Generated by Django 5.1.4 on 2025-01-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0003_review_img_alter_items_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='img',
            field=models.ImageField(upload_to='items/'),
        ),
    ]
