# Generated by Django 5.1.4 on 2025-01-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0004_alter_items_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=25)),
                ('mobile', models.IntegerField()),
                ('add', models.TextField()),
                ('passs', models.CharField(max_length=100)),
            ],
        ),
    ]
