# Generated by Django 5.1.4 on 2025-01-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0005_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='profileDB',
        ),
    ]
